services:
  camireads-api:
    build:
      context: .          # ðŸ‘ˆ usar la carpeta actual como contexto
      dockerfile: Dockerfile
    container_name: camireads-api
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.1.87:5433/camireads
      SPRING_DATASOURCE_USERNAME: camireads_user
      SPRING_DATASOURCE_PASSWORD: camireads_pass
    ports:
      - "9095:8080"
